version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6020
      DatabaseServer: mssqlserver
      DatabaseName: EventsDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6020:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webclientmvc
    build:
      context: .\WebClientMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.1.133:6022
      CallBackUrl: http://localhost:6021
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_51HDhVlJLmeYdqvSN2Yhjly4qoG5AprR653aACX9J41DtcLlhnXGf7qsqSHjJ8t1xrPPOOY9VvwgR6XaSQDmXFwFr00y4MA4r2Q
      StripePrivateKey: sk_test_51HDhVlJLmeYdqvSNQKrJteTYcGVxxaZmZluKdc1jWOG4FHLkpmQVZFxHDULqXpzWqEfrj6jAXz1xF3BNOWBO9IgC00Ju2AxD8N
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "6021:80"
    container_name: eventShop
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - tokenserver
      - order

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderappi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.133:6022
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6033:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      Mvcclient: http://localhost:6021
    ports:
      - "6022:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      IdentityUrl: http://192.168.1.133:6022
      ConnectionString: basket.data
    ports:
      - "6023:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1440:1433"
    container_name: eventssqlserver
    networks:
      - backend

  basket.data:
    image: redis
    container_name: basketdatas
    ports:
      - "6024:6379"
    networks:
      - backend